CREATE TABLE AlertMessageTable
(	"UID" VARCHAR2(128 BYTE) NOT NULL ENABLE,
   "BODY" VARCHAR2(4000 BYTE) NOT NULL ENABLE
);

CREATE TABLE OUTPUT_TABLE(
  "RCD_ID" NUMBER(*,0) NOT NULL ENABLE,
  "CRT_TS" VARCHAR2(128 BYTE) NOT NULL ENABLE,
  PUBL_NM VARCHAR2(128 BYTE) NOT NULL ENABLE,
  TPC VARCHAR2(128 BYTE) NOT NULL ENABLE,
  SUB_TPC VARCHAR2(128 BYTE) NOT NULL ENABLE,
  SUB_TPC_2_CD VARCHAR2(128 BYTE) NOT NULL ENABLE,
  SUB_TPC_3_CD VARCHAR2(128 BYTE) NOT NULL ENABLE,
  SUB_TPC_4_CD VARCHAR2(128 BYTE) NOT NULL ENABLE,
  SUB_TPC_5_CD VARCHAR2(128 BYTE) NOT NULL ENABLE,
  ACTN_STNG VARCHAR2(640 BYTE) NOT NULL ENABLE);
